### ISSUE TITLE
`cal q3` doesn't highlight current day

### ISSUE THREAD

**Issue by hjdivad** [rwjblue/cal-rs#18]
![image](https://github.com/rwjblue/cal-rs/assets/17980/e53a38c3-c90e-4159-a8dd-68f621e528c7)

![image](https://github.com/rwjblue/cal-rs/assets/17980/f842cf9c-ee8d-4e87-beef-9dcbb1ee6e15)

**Comment by rwjblue** [comment]
`cal q3` shouldn't include the current date (since Q3 is from July through September), right? It definitely should highlight the current date in any of the cases where the current day is included in the range though.

**Comment by hjdivad** [comment]
you might be on to something there rob 🤣
